#!/bin/bash
# KPI Command Reference
# Все команды для запуска KPI анализа в одном месте

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     📝 КОМАНДЫ ДЛЯ ЗАПУСКА KPI АНАЛИЗА - ШПАРГАЛКА           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "🎯 ОСНОВНЫЕ КОМАНДЫ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Интерактивный анализ (вставить текст вручную):"
echo "     $ python run_kpi_analyzer.py"
echo ""
echo "  2. Проверить что всё работает:"
echo "     $ python verify_kpi_module.py"
echo ""
echo "  3. Запустить полные тесты:"
echo "     $ ./kpi.sh test"
echo "     или"
echo "     $ python app/backend/calls_kpi_evaluation/test_kpi.py"
echo ""

echo "⚡ БЫСТРЫЕ КОМАНДЫ ЧЕРЕЗ BASH:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ./kpi.sh verify       → Проверить компоненты"
echo "  ./kpi.sh test         → Запустить тесты"
echo "  ./kpi.sh run          → Интерактивный анализатор"
echo "  ./kpi.sh example      → Пример использования"
echo "  ./kpi.sh batch        → Обработать пакет файлов"
echo "  ./kpi.sh results      → Просмотреть результаты"
echo "  ./kpi.sh help         → Справка"
echo ""

echo "💡 ПРИМЕРЫ КОМАНДНОЙ СТРОКИ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Анализ текста напрямую (Python):"
echo "  $ python -c \"from app.backend.calls_kpi_evaluation import analyze_call; \\"
echo "    print(analyze_call('Менеджер: Здравствуйте'))['overall_score']\""
echo ""
echo "  Анализ из JSON файла:"
echo "  $ python app/backend/calls_kpi_evaluation/example_usage.py"
echo ""
echo "  Обработка пакета файлов:"
echo "  $ python app/backend/calls_kpi_evaluation/pipeline_integration.py"
echo ""

echo "📊 РЕЗУЛЬТАТЫ СОХРАНЯЮТСЯ В:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  $ ls data/kpi_analysis/"
echo ""

echo "📖 ДОКУМЕНТАЦИЯ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  $ cat KPI_QUICK_START.md              (Шпаргалка)"
echo "  $ cat KPI_ANALYSIS_FINAL_DOCUMENTATION.md"
echo "  $ cat app/backend/calls_kpi_evaluation/README.md"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo ""
